"""
Run this ONCE before starting Docker containers.
Generates JWT_SECRET, ANON_KEY, SERVICE_ROLE_KEY and writes .env

Usage:
    py generate_keys.py
"""

import secrets
import time
import base64
import hmac
import hashlib
import json
import os


def b64url_encode(data: bytes) -> str:
    return base64.urlsafe_b64encode(data).rstrip(b"=").decode()


def make_jwt(payload: dict, secret: str) -> str:
    header = {"alg": "HS256", "typ": "JWT"}
    header_b64 = b64url_encode(json.dumps(header, separators=(",", ":")).encode())
    payload_b64 = b64url_encode(json.dumps(payload, separators=(",", ":")).encode())
    signing_input = f"{header_b64}.{payload_b64}".encode()
    signature = hmac.new(secret.encode(), signing_input, hashlib.sha256).digest()
    return f"{header_b64}.{payload_b64}.{b64url_encode(signature)}"


def main():
    env_path = os.path.join(os.path.dirname(__file__), ".env")

    if os.path.exists(env_path):
        print(f".env already exists at {env_path}")
        overwrite = input("Overwrite? (y/N): ").strip().lower()
        if overwrite != "y":
            print("Aborted.")
            return

    jwt_secret = secrets.token_urlsafe(48)  # 64-char secret
    postgres_password = secrets.token_urlsafe(24)

    iat = 1641769200  # fixed issued-at (Supabase convention)
    exp = 9999999999  # far future

    anon_payload = {"role": "anon", "iss": "supabase", "iat": iat, "exp": exp}
    service_payload = {"role": "service_role", "iss": "supabase", "iat": iat, "exp": exp}

    anon_key = make_jwt(anon_payload, jwt_secret)
    service_key = make_jwt(service_payload, jwt_secret)

    env_content = f"""# ============================================================
# Generated by generate_keys.py — do NOT commit this file
# ============================================================

# --- PostgreSQL ---
POSTGRES_PASSWORD={postgres_password}
DB_HOST=localhost
DB_PORT=5432
DB_NAME=postgres
DB_USER=postgres
DB_PASSWORD={postgres_password}

# --- Supabase Auth ---
JWT_SECRET={jwt_secret}
ANON_KEY={anon_key}
SERVICE_ROLE_KEY={service_key}

# --- LLM Provider ---
# "lmstudio"  -> fully offline, uses LM Studio running locally
# "claude"    -> uses Anthropic API (requires ANTHROPIC_API_KEY + internet)
LLM_PROVIDER=lmstudio

# --- LM Studio ---
# Start Local Server in LM Studio (Settings -> Local Server -> Start Server)
LM_STUDIO_URL=http://localhost:1234/v1
LM_STUDIO_MODEL=local-model

# --- Claude (Anthropic API) ---
# Only needed when LLM_PROVIDER=claude
# Get your key at: https://console.anthropic.com/
ANTHROPIC_API_KEY=
CLAUDE_MODEL=claude-sonnet-4-6

# --- Embeddings (offline after first run) ---
EMBEDDING_MODEL=all-MiniLM-L6-v2
EMBEDDING_DIM=384

# --- Chunking ---
CHUNK_SIZE=512
CHUNK_OVERLAP=64
"""

    with open(env_path, "w", encoding="utf-8") as f:
        f.write(env_content)

    print(f"\n.env written to: {env_path}")
    print("Next steps:")
    print("  1. docker compose up -d")
    print("  2. py main.py ingest <path/to/document.txt>")
    print("  3. py main.py build-graph")
    print("  4. py main.py query \"Your question here\"")


if __name__ == "__main__":
    main()
