"""
Graph RAG — Interactive Installer
Run this after cloning the repo:  python install.py
"""

import os
import sys
import shutil
import subprocess
import platform
import secrets
import time
import base64
import hmac
import hashlib
import json

# ── Helpers ────────────────────────────────────────────────────────────────────

ROOT = os.path.dirname(os.path.abspath(__file__))
PY  = sys.executable          # same interpreter that launched this script


def header(title: str):
    print(f"\n{'=' * 60}")
    print(f"  {title}")
    print(f"{'=' * 60}")


def step(n: int, total: int, msg: str):
    print(f"\n[{n}/{total}] {msg}")
    print("-" * 40)


def ok(msg: str):
    print(f"  OK  {msg}")


def info(msg: str):
    print(f"  >>  {msg}")


def warn(msg: str):
    print(f"  !!  {msg}")


def ask(prompt: str, choices: list[str] | None = None, default: str = "") -> str:
    """Prompt user and return their answer (stripped, lowercased)."""
    if choices:
        options = "/".join(
            c.upper() if c == default else c for c in choices
        )
        prompt = f"{prompt} [{options}]: "
    else:
        prompt = f"{prompt}: "
    while True:
        answer = input(prompt).strip()
        if not answer and default:
            return default.lower()
        if choices:
            if answer.lower() in [c.lower() for c in choices]:
                return answer.lower()
            print(f"  Please enter one of: {', '.join(choices)}")
        else:
            return answer


def run(cmd: list[str], check: bool = True, capture: bool = False) -> subprocess.CompletedProcess:
    """Run a shell command, printing it first."""
    info("Running: " + " ".join(cmd))
    result = subprocess.run(
        cmd,
        capture_output=capture,
        text=True,
    )
    if check and result.returncode != 0:
        warn(f"Command failed (exit {result.returncode})")
        if capture and result.stderr:
            print(result.stderr)
        sys.exit(1)
    return result


def cmd_exists(name: str) -> bool:
    return shutil.which(name) is not None


def docker_running() -> bool:
    """Return True if Docker daemon is reachable."""
    try:
        result = subprocess.run(
            ["docker", "info"],
            capture_output=True, text=True, timeout=10,
        )
        return result.returncode == 0
    except Exception:
        return False


# ── Key generation (mirrors generate_keys.py) ──────────────────────────────────

def b64url(data: bytes) -> str:
    return base64.urlsafe_b64encode(data).rstrip(b"=").decode()


def make_jwt(payload: dict, secret: str) -> str:
    header = b64url(json.dumps({"alg": "HS256", "typ": "JWT"}, separators=(",", ":")).encode())
    body   = b64url(json.dumps(payload, separators=(",", ":")).encode())
    sig    = b64url(hmac.new(secret.encode(), f"{header}.{body}".encode(), hashlib.sha256).digest())
    return f"{header}.{body}.{sig}"


def write_env(db_password: str, jwt_secret: str = "", anon_key: str = "",
              service_key: str = "", llm_provider: str = "lmstudio"):
    env_path = os.path.join(ROOT, ".env")
    content = f"""# ============================================================
# Generated by install.py — do NOT commit this file
# ============================================================

# --- PostgreSQL ---
POSTGRES_PASSWORD={db_password}
DB_HOST=localhost
DB_PORT=5432
DB_NAME=postgres
DB_USER=postgres
DB_PASSWORD={db_password}

# --- Supabase Auth (only needed for Docker/Supabase stack) ---
JWT_SECRET={jwt_secret}
ANON_KEY={anon_key}
SERVICE_ROLE_KEY={service_key}

# --- LLM Provider ---
# "lmstudio"  -> fully offline, uses LM Studio running locally
# "claude"    -> uses Anthropic API (requires ANTHROPIC_API_KEY + internet)
LLM_PROVIDER={llm_provider}

# --- LM Studio ---
LM_STUDIO_URL=http://localhost:1234/v1
LM_STUDIO_MODEL=local-model

# --- Claude (Anthropic API) ---
ANTHROPIC_API_KEY=
CLAUDE_MODEL=claude-sonnet-4-6

# --- Embeddings ---
EMBEDDING_MODEL=all-MiniLM-L6-v2
EMBEDDING_DIM=384

# --- Chunking ---
CHUNK_SIZE=512
CHUNK_OVERLAP=64
"""
    with open(env_path, "w", encoding="utf-8") as f:
        f.write(content)
    ok(f".env written to {env_path}")


# ── Install steps (shared) ─────────────────────────────────────────────────────

def install_python_deps():
    run([PY, "-m", "pip", "install", "--upgrade", "pip", "-q"])
    run([PY, "-m", "pip", "install", "-r", os.path.join(ROOT, "requirements.txt")])
    ok("Python dependencies installed.")


def download_nlp_models():
    info("Downloading spaCy model (en_core_web_sm)...")
    run([PY, "-m", "spacy", "download", "en_core_web_sm"])

    info("Downloading NLTK data...")
    run([PY, "-c", "import nltk; nltk.download('punkt'); nltk.download('punkt_tab')"])

    info("Pre-caching sentence-transformers embedding model...")
    run([PY, "-c",
         "from sentence_transformers import SentenceTransformer; "
         "SentenceTransformer('all-MiniLM-L6-v2'); print('  Cached.')"])
    ok("NLP models ready.")


def register_mcp(detected_os: str):
    print()
    answer = ask("Register the Graph RAG MCP server with Claude Code?", ["y", "n"], default="y")
    if answer != "y":
        info("Skipped. To register later:")
        info(f"  claude mcp add graph-rag -s user -- {PY} mcp_server.py")
        info("  (Run from the graph_rag directory)")
        return

    if not cmd_exists("claude"):
        warn("'claude' command not found — Claude Code may not be installed or not on PATH.")
        info("To register manually once Claude Code is installed:")
        info(f"  cd {ROOT}")
        info(f"  claude mcp add graph-rag -s user -- {PY} mcp_server.py")
        return

    run(["claude", "mcp", "add", "graph-rag", "-s", "user",
         "--", PY, os.path.join(ROOT, "mcp_server.py")])
    ok("Graph RAG MCP server registered with Claude Code.")


def print_final_summary(mode: str):
    header("Installation Complete!")
    print(f"""
  Mode      : {mode}
  Directory : {ROOT}

  Quick start:
    python chat.py                          — start chatting
    python main.py ingest <file>            — add a document
    python main.py stats                    — check knowledge base
    python main.py query "your question"    — ask without chat UI

  LLM provider (edit .env to switch):
    LLM_PROVIDER=lmstudio   — fully offline (LM Studio must be running)
    LLM_PROVIDER=claude     — Anthropic API (set ANTHROPIC_API_KEY in .env)

  See COMMANDS.txt for the full reference.
""")


# ── Docker path ────────────────────────────────────────────────────────────────

def install_docker_path(detected_os: str, total_steps: int = 6):
    header("Installation via Docker")

    # Step 1 — Generate secrets
    step(1, total_steps, "Generating secrets (.env)")
    env_path = os.path.join(ROOT, ".env")
    if os.path.exists(env_path):
        answer = ask(".env already exists. Regenerate?", ["y", "n"], default="n")
        if answer == "y":
            _generate_secrets_docker()
        else:
            ok("Keeping existing .env")
    else:
        _generate_secrets_docker()

    # Step 2 — Start containers
    step(2, total_steps, "Starting Docker containers (docker compose up -d)")
    run(["docker", "compose", "up", "-d"], check=True)
    info("Waiting 10 s for the database to initialize...")
    time.sleep(10)
    ok("Containers started.")

    # Step 3 — Python deps
    step(3, total_steps, "Installing Python dependencies")
    install_python_deps()

    # Step 4 — NLP models
    step(4, total_steps, "Downloading NLP & embedding models (one-time)")
    download_nlp_models()

    # Step 5 — MCP registration
    step(5, total_steps, "Claude Code MCP registration")
    register_mcp(detected_os)

    # Step 6 — Done
    step(6, total_steps, "Verifying database connection")
    _verify_db()

    print_final_summary("Docker (Supabase stack)")


def _generate_secrets_docker():
    db_pass    = secrets.token_urlsafe(24)
    jwt_secret = secrets.token_urlsafe(48)
    iat, exp   = 1641769200, 9999999999
    anon_key   = make_jwt({"role": "anon",         "iss": "supabase", "iat": iat, "exp": exp}, jwt_secret)
    svc_key    = make_jwt({"role": "service_role", "iss": "supabase", "iat": iat, "exp": exp}, jwt_secret)
    write_env(db_pass, jwt_secret, anon_key, svc_key)


def _verify_db():
    try:
        result = subprocess.run(
            [PY, "-c",
             "import sys; sys.path.insert(0,'.'); "
             "from db.connection import get_conn; "
             "from db.queries import get_stats; "
             "conn_ctx = get_conn(); conn = conn_ctx.__enter__(); "
             "s = get_stats(conn); print('Documents:', s['documents'])"],
            capture_output=True, text=True, cwd=ROOT,
        )
        if result.returncode == 0:
            ok("Database connection successful.")
        else:
            warn("Could not connect to database. The containers may still be starting.")
            info("Try again in 30 s: python main.py stats")
    except Exception as e:
        warn(f"Verification skipped: {e}")


# ── Native path ────────────────────────────────────────────────────────────────

def install_native_path(detected_os: str, total_steps: int = 7):
    header("Installation — Native PostgreSQL (no Docker)")

    # Step 1 — Install PostgreSQL + pgvector
    step(1, total_steps, "Installing PostgreSQL + pgvector")
    _install_postgres_native(detected_os)

    # Step 2 — Generate secrets (DB only, no JWT)
    step(2, total_steps, "Generating secrets (.env)")
    env_path = os.path.join(ROOT, ".env")
    if os.path.exists(env_path):
        answer = ask(".env already exists. Regenerate?", ["y", "n"], default="n")
        if answer == "y":
            write_env(secrets.token_urlsafe(24))
        else:
            ok("Keeping existing .env")
    else:
        write_env(secrets.token_urlsafe(24))

    # Step 3 — Set DB password & init schema
    step(3, total_steps, "Initialising database schema")
    _init_native_db(detected_os)

    # Step 4 — Python deps
    step(4, total_steps, "Installing Python dependencies")
    install_python_deps()

    # Step 5 — NLP models
    step(5, total_steps, "Downloading NLP & embedding models (one-time)")
    download_nlp_models()

    # Step 6 — MCP registration
    step(6, total_steps, "Claude Code MCP registration")
    register_mcp(detected_os)

    # Step 7 — Done
    step(7, total_steps, "Verifying database connection")
    _verify_db()

    print_final_summary("Native PostgreSQL")


def _install_postgres_native(detected_os: str):
    if detected_os == "macos":
        if not cmd_exists("brew"):
            warn("Homebrew not found. Install it first: https://brew.sh")
            sys.exit(1)
        info("Installing PostgreSQL and pgvector via Homebrew...")
        run(["brew", "install", "postgresql@15", "pgvector"])
        run(["brew", "services", "start", "postgresql@15"])
        ok("PostgreSQL started.")

    elif detected_os == "linux":
        info("Installing PostgreSQL via apt...")
        run(["sudo", "apt-get", "update", "-qq"])
        run(["sudo", "apt-get", "install", "-y", "-qq",
             "postgresql", "postgresql-contrib", "libpq-dev"])

        # Try apt for pgvector first (Ubuntu 24.04+), else build from source
        result = run(
            ["sudo", "apt-get", "install", "-y", "-qq", "postgresql-16-pgvector"],
            check=False,
        )
        if result.returncode != 0:
            info("apt pgvector not available — building from source...")
            _build_pgvector_linux()

        run(["sudo", "systemctl", "enable", "--now", "postgresql"])
        ok("PostgreSQL started.")

    elif detected_os == "windows":
        if cmd_exists("winget"):
            info("Installing PostgreSQL via winget...")
            run(["winget", "install", "--id", "PostgreSQL.PostgreSQL", "-e", "--silent"])
        else:
            warn("winget not available.")
            print("""
  Please install PostgreSQL manually:
    https://www.postgresql.org/download/windows/

  Make sure to:
    1. Add PostgreSQL bin/ to your PATH
    2. Note the password you set for the 'postgres' user

  Then re-run this installer.
""")
            input("Press Enter once PostgreSQL is installed...")

        # pgvector on Windows must be installed manually
        warn("pgvector must be installed separately on Windows.")
        print("""
  Download the pgvector Windows installer:
    https://github.com/pgvector/pgvector#installation

  Or install via Stack Builder (included with PostgreSQL installer).
""")
        input("Press Enter once pgvector is installed...")
        ok("PostgreSQL ready (assumed).")


def _build_pgvector_linux():
    """Build and install pgvector from source (Linux fallback)."""
    run(["sudo", "apt-get", "install", "-y", "-qq",
         "build-essential", "postgresql-server-dev-all", "git"])
    tmp = "/tmp/pgvector"
    if not os.path.exists(tmp):
        run(["git", "clone", "--depth", "1",
             "https://github.com/pgvector/pgvector.git", tmp])
    run(["make", "-C", tmp])
    run(["sudo", "make", "-C", tmp, "install"])
    ok("pgvector built and installed from source.")


def _init_native_db(detected_os: str):
    """Read the generated password from .env and apply it + init.sql."""
    # Read password from .env
    db_password = ""
    env_path = os.path.join(ROOT, ".env")
    with open(env_path, encoding="utf-8") as f:
        for line in f:
            if line.startswith("DB_PASSWORD="):
                db_password = line.split("=", 1)[1].strip()
                break

    if not db_password:
        warn("Could not read DB_PASSWORD from .env")
        sys.exit(1)

    sql_path = os.path.join(ROOT, "sql", "init.sql")

    if detected_os == "windows":
        psql = shutil.which("psql") or r"C:\Program Files\PostgreSQL\17\bin\psql.exe"
    else:
        psql = shutil.which("psql") or "psql"

    if not os.path.exists(psql) and not cmd_exists("psql"):
        warn(f"psql not found at: {psql}")
        info("Make sure PostgreSQL bin/ is on your PATH.")
        sys.exit(1)

    # Set the postgres user password to match our generated one
    set_pw_sql = f"ALTER USER postgres PASSWORD '{db_password}';"

    env = os.environ.copy()
    env["PGPASSWORD"] = db_password

    # Apply password (connect as current user on Linux/macOS, or trust on Windows)
    if detected_os in ("linux", "macos"):
        run(["sudo", "-u", "postgres", psql, "-c", set_pw_sql])
    else:
        run([psql, "-U", "postgres", "-c", set_pw_sql], check=False)

    # Run schema
    if detected_os in ("linux", "macos"):
        subprocess.run(
            ["sudo", "-u", "postgres", psql, "-f", sql_path],
            check=True,
        )
    else:
        env_with_pw = os.environ.copy()
        env_with_pw["PGPASSWORD"] = db_password
        subprocess.run(
            [psql, "-U", "postgres", "-f", sql_path],
            env=env_with_pw,
            check=True,
        )
    ok("Database schema initialised.")


# ── Main ───────────────────────────────────────────────────────────────────────

def main():
    header("Graph RAG — Installer")
    print("""
  This installer will:
    1. Detect (or ask) your platform and Docker availability
    2. Set up PostgreSQL + pgvector (via Docker or natively)
    3. Generate secure credentials (.env)
    4. Install Python dependencies
    5. Download NLP and embedding models
    6. Optionally register the MCP server with Claude Code
""")

    # ── Q1: Platform ───────────────────────────────────────────────────────────

    auto_os = platform.system().lower()
    os_map  = {"darwin": "macos", "linux": "linux", "windows": "windows"}
    detected = os_map.get(auto_os, "")

    print("Question 1 of 2 — Platform")
    print(f"  Auto-detected: {detected or 'unknown'}")
    choices_os = ["windows", "macos", "linux"]

    if detected:
        answer_os = ask(
            f"  Is this correct?  (Enter to confirm, or type to change)",
            choices_os,
            default=detected,
        )
    else:
        answer_os = ask("  Select your platform", choices_os)

    ok(f"Platform: {answer_os}")

    # ── Q2: Docker ─────────────────────────────────────────────────────────────

    print("\nQuestion 2 of 2 — Docker")
    has_docker_cmd = cmd_exists("docker")
    docker_ok      = has_docker_cmd and docker_running()

    if docker_ok:
        info("Docker detected and running.")
    elif has_docker_cmd:
        info("Docker is installed but the daemon is not running.")
        info("Start Docker Desktop (or the Docker service) and try again,")
        info("or choose native installation instead.")
    else:
        info("Docker not found on this machine.")

    answer_docker = ask(
        "  Install via Docker?",
        ["y", "n"],
        default="y" if docker_ok else "n",
    )

    if answer_docker == "y" and not docker_ok:
        warn("Docker daemon is not reachable.")
        confirm = ask("  Proceed anyway? (containers may fail to start)", ["y", "n"], default="n")
        if confirm != "y":
            info("Please start Docker and re-run the installer.")
            sys.exit(0)

    print()

    # ── Route to install path ──────────────────────────────────────────────────

    os.chdir(ROOT)   # ensure relative paths (docker compose, etc.) work

    if answer_docker == "y":
        install_docker_path(answer_os)
    else:
        install_native_path(answer_os)


if __name__ == "__main__":
    try:
        main()
    except KeyboardInterrupt:
        print("\n\n  Installation cancelled.")
        sys.exit(0)
